openapi: 3.2.0
info:
  version: '2018-09-22'
  x-release: v4
  title: CodeArtifact Packages#domain&repository API
  description: CodeArtifact is a fully managed artifact repository compatible with language-native package managers and build tools such as npm, Apache Maven, pip, and dotnet.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: codeartifact
  x-aws-signingName: codeartifact
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/codeartifact-2018-09-22.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://codeartifact.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodeArtifact multi-region endpoint
- url: https://codeartifact.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodeArtifact multi-region endpoint
- url: http://codeartifact.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodeArtifact endpoint for China (Beijing) and China (Ningxia)
- url: https://codeartifact.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodeArtifact endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Packages#domain&repository
paths:
  /v1/packages#domain&repository:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListPackages
      description: Returns a list of PackageSummary objects for packages in a repository that match the request parameters.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListPackagesResult'
              examples:
                ListPackages200Example:
                  summary: Default ListPackages 200 response
                  x-microcks-default: true
                  value:
                    packages: lodash
                    nextToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.example
        '480':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                ListPackages480Example:
                  summary: Default ListPackages 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
              examples:
                ListPackages481Example:
                  summary: Default ListPackages 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                ListPackages482Example:
                  summary: Default ListPackages 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
              examples:
                ListPackages483Example:
                  summary: Default ListPackages 483 response
                  x-microcks-default: true
                  value: example-value
        '484':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
              examples:
                ListPackages484Example:
                  summary: Default ListPackages 484 response
                  x-microcks-default: true
                  value: '500123'
      parameters:
      - name: domain
        in: query
        required: true
        description: ' The name of the domain that contains the repository that contains the requested packages. '
        schema:
          type: string
          pattern: '[a-z][a-z0-9\-]{0,48}[a-z0-9]'
          minLength: 2
          maxLength: 50
      - name: domain-owner
        in: query
        required: false
        description: ' The 12-digit account number of the Amazon Web Services account that owns the domain. It does not include dashes or spaces. '
        schema:
          type: string
          pattern: '[0-9]{12}'
          minLength: 12
          maxLength: 12
      - name: repository
        in: query
        required: true
        description: ' The name of the repository that contains the requested packages. '
        schema:
          type: string
          pattern: '[A-Za-z0-9][A-Za-z0-9._\-]{1,99}'
          minLength: 2
          maxLength: 100
      - name: format
        in: query
        required: false
        description: The format used to filter requested packages. Only packages from the provided format will be returned.
        schema:
          type: string
          enum:
          - npm
          - pypi
          - maven
          - nuget
          - generic
      - name: namespace
        in: query
        required: false
        description: <p>The namespace prefix used to filter requested packages. Only packages with a namespace that starts with the provided string value are returned. Note that although this option is called <code>--namespace</code> and not <code>--namespace-prefix</code>, it has prefix-matching behavior.</p> <p>Each package format uses namespace as follows:</p> <ul> <li> <p> The namespace of a Maven package is its <code>groupId</code>. </p> </li> <li> <p> The namespace of an npm package is its <code>scope</code>. </p> </li> <li> <p> Python and NuGet packages do not contain a corresponding component, packages of those formats do not have a namespace. </p> </li> <li> <p> The namespace of a generic package is its <code>namespace</code>. </p> </li> </ul>
        schema:
          type: string
          pattern: '[^#/\s]+'
          minLength: 1
          maxLength: 255
      - name: package-prefix
        in: query
        required: false
        description: ' A prefix used to filter requested packages. Only packages with names that start with <code>packagePrefix</code> are returned. '
        schema:
          type: string
          pattern: '[^#/\s]+'
          minLength: 1
          maxLength: 255
      - name: max-results
        in: query
        required: false
        description: ' The maximum number of results to return per page. '
        schema:
          type: integer
          minimum: 1
          maximum: 1000
      - name: next-token
        in: query
        required: false
        description: ' The token for the next set of results. Use the value returned in the previous response in the next request to retrieve the next set of results. '
        schema:
          type: string
          pattern: \S+
          minLength: 1
          maxLength: 2000
      - name: publish
        in: query
        required: false
        description: The value of the <code>Publish</code> package origin control restriction used to filter requested packages. Only packages with the provided restriction are returned. For more information, see <a href="https://docs.aws.amazon.com/codeartifact/latest/APIReference/API_PackageOriginRestrictions.html">PackageOriginRestrictions</a>.
        schema:
          type: string
          enum:
          - ALLOW
          - BLOCK
      - name: upstream
        in: query
        required: false
        description: The value of the <code>Upstream</code> package origin control restriction used to filter requested packages. Only packages with the provided restriction are returned. For more information, see <a href="https://docs.aws.amazon.com/codeartifact/latest/APIReference/API_PackageOriginRestrictions.html">PackageOriginRestrictions</a>.
        schema:
          type: string
          enum:
          - ALLOW
          - BLOCK
      - name: maxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: nextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      summary: Amazon CodeArtifact List Packages
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Packages#domain&repository
components:
  schemas:
    PackageSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/PackageSummary'
    ThrottlingException: {}
    PackageOriginConfiguration:
      type: object
      properties:
        restrictions:
          allOf:
          - $ref: '#/components/schemas/PackageOriginRestrictions'
          - description: A <code>PackageOriginRestrictions</code> object that contains information about the upstream and publish package origin configuration for the package.
      description: Details about the package origin configuration of a package.
    ValidationException: {}
    PackageName:
      type: string
      pattern: '[^#/\s]+'
      minLength: 1
      maxLength: 255
    PackageFormat:
      type: string
      enum:
      - npm
      - pypi
      - maven
      - nuget
      - generic
    AllowUpstream:
      type: string
      enum:
      - ALLOW
      - BLOCK
    ResourceNotFoundException: {}
    ListPackagesResult:
      type: object
      properties:
        packages:
          allOf:
          - $ref: '#/components/schemas/PackageSummaryList'
          - description: ' The list of returned <a href="https://docs.aws.amazon.com/codeartifact/latest/APIReference/API_PackageSummary.html">PackageSummary</a> objects. '
        nextToken:
          allOf:
          - $ref: '#/components/schemas/PaginationToken'
          - description: ' If there are additional results, this is the token for the next set of results. '
    PaginationToken:
      type: string
      pattern: \S+
      minLength: 1
      maxLength: 2000
    PackageSummary:
      type: object
      properties:
        format:
          allOf:
          - $ref: '#/components/schemas/PackageFormat'
          - description: ' The format of the package. '
        namespace:
          allOf:
          - $ref: '#/components/schemas/PackageNamespace'
          - description: <p>The namespace of the package. The package component that specifies its namespace depends on its type. For example:</p> <ul> <li> <p> The namespace of a Maven package is its <code>groupId</code>. </p> </li> <li> <p> The namespace of an npm package is its <code>scope</code>. </p> </li> <li> <p> Python and NuGet packages do not contain a corresponding component, packages of those formats do not have a namespace. </p> </li> <li> <p> The namespace of a generic package is its <code>namespace</code>. </p> </li> </ul>
        package:
          allOf:
          - $ref: '#/components/schemas/PackageName'
          - description: ' The name of the package. '
        originConfiguration:
          allOf:
          - $ref: '#/components/schemas/PackageOriginConfiguration'
          - description: A <a href="https://docs.aws.amazon.com/codeartifact/latest/APIReference/API_PackageOriginConfiguration.html">PackageOriginConfiguration</a> object that contains a <a href="https://docs.aws.amazon.com/codeartifact/latest/APIReference/API_PackageOriginRestrictions.html">PackageOriginRestrictions</a> object that contains information about the upstream and publish package origin restrictions.
      description: ' Details about a package, including its format, namespace, and name. '
    InternalServerException: {}
    PackageOriginRestrictions:
      type: object
      required:
      - publish
      - upstream
      properties:
        publish:
          allOf:
          - $ref: '#/components/schemas/AllowPublish'
          - description: The package origin configuration that determines if new versions of the package can be published directly to the repository.
        upstream:
          allOf:
          - $ref: '#/components/schemas/AllowUpstream'
          - description: The package origin configuration that determines if new versions of the package can be added to the repository from an external connection or upstream source.
      description: Details about the origin restrictions set on the package. The package origin restrictions determine how new versions of a package can be added to a specific repository.
    AllowPublish:
      type: string
      enum:
      - ALLOW
      - BLOCK
    AccessDeniedException: {}
    PackageNamespace:
      type: string
      pattern: '[^#/\s]+'
      minLength: 1
      maxLength: 255
  parameters:
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/codeartifact/
x-hasEquivalentPaths: true
