openapi: 3.2.0
info:
  version: '2018-09-22'
  x-release: v4
  title: CodeArtifact Domains API
  description: CodeArtifact is a fully managed artifact repository compatible with language-native package managers and build tools such as npm, Apache Maven, pip, and dotnet.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: codeartifact
  x-aws-signingName: codeartifact
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/codeartifact-2018-09-22.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://codeartifact.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodeArtifact multi-region endpoint
- url: https://codeartifact.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodeArtifact multi-region endpoint
- url: http://codeartifact.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodeArtifact endpoint for China (Beijing) and China (Ningxia)
- url: https://codeartifact.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodeArtifact endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Domains
paths:
  /v1/domains:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListDomains
      description: Returns a list of DomainSummary objects for all domains owned by the Amazon Web Services account that makes this call. Each returned DomainSummary object contains information about a domain.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListDomainsResult'
              examples:
                ListDomains200Example:
                  summary: Default ListDomains 200 response
                  x-microcks-default: true
                  value:
                    domains: my-domain
                    nextToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.example
        '480':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                ListDomains480Example:
                  summary: Default ListDomains 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
              examples:
                ListDomains481Example:
                  summary: Default ListDomains 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
              examples:
                ListDomains482Example:
                  summary: Default ListDomains 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
              examples:
                ListDomains483Example:
                  summary: Default ListDomains 483 response
                  x-microcks-default: true
                  value: '500123'
      parameters:
      - name: maxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: nextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                maxResults:
                  description: ' The maximum number of results to return per page. '
                  type: integer
                  minimum: 1
                  maximum: 1000
                nextToken:
                  description: ' The token for the next set of results. Use the value returned in the previous response in the next request to retrieve the next set of results. '
                  type: string
                  pattern: \S+
                  minLength: 1
                  maxLength: 2000
            examples:
              ListDomainsRequestExample:
                summary: Default ListDomains request
                x-microcks-default: true
                value:
                  maxResults: 1
                  nextToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.example
      summary: Amazon CodeArtifact List Domains
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Domains
components:
  parameters:
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
  schemas:
    ThrottlingException: {}
    DomainSummary:
      type: object
      properties:
        name:
          allOf:
          - $ref: '#/components/schemas/DomainName'
          - description: ' The name of the domain. '
        owner:
          allOf:
          - $ref: '#/components/schemas/AccountId'
          - description: ' The 12-digit account number of the Amazon Web Services account that owns the domain. It does not include dashes or spaces. '
        arn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: ' The ARN of the domain. '
        status:
          allOf:
          - $ref: '#/components/schemas/DomainStatus'
          - description: ' A string that contains the status of the domain. '
        createdTime:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: ' A timestamp that contains the date and time the domain was created. '
        encryptionKey:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: ' The key used to encrypt the domain. '
      description: ' Information about a domain, including its name, Amazon Resource Name (ARN), and status. The <a href="https://docs.aws.amazon.com/codeartifact/latest/APIReference/API_ListDomains.html">ListDomains</a> operation returns a list of <code>DomainSummary</code> objects. '
    AccountId:
      type: string
      pattern: '[0-9]{12}'
      minLength: 12
      maxLength: 12
    Arn:
      type: string
      pattern: \S+
      minLength: 1
      maxLength: 1011
    DomainSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/DomainSummary'
    ValidationException: {}
    DomainStatus:
      type: string
      enum:
      - Active
      - Deleted
    PaginationToken:
      type: string
      pattern: \S+
      minLength: 1
      maxLength: 2000
    InternalServerException: {}
    AccessDeniedException: {}
    ListDomainsResult:
      type: object
      properties:
        domains:
          allOf:
          - $ref: '#/components/schemas/DomainSummaryList'
          - description: ' The returned list of <a href="https://docs.aws.amazon.com/codeartifact/latest/APIReference/API_DomainSummary.html">DomainSummary</a> objects. '
        nextToken:
          allOf:
          - $ref: '#/components/schemas/PaginationToken'
          - description: ' The token for the next set of results. Use the value returned in the previous response in the next request to retrieve the next set of results. '
    DomainName:
      type: string
      pattern: '[a-z][a-z0-9\-]{0,48}[a-z0-9]'
      minLength: 2
      maxLength: 50
    Timestamp:
      type: string
      format: date-time
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/codeartifact/
x-hasEquivalentPaths: true
