openapi: 3.2.0
info:
  version: '2018-09-22'
  x-release: v4
  title: CodeArtifact Repositories API
  description: CodeArtifact is a fully managed artifact repository compatible with language-native package managers and build tools such as npm, Apache Maven, pip, and dotnet.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: codeartifact
  x-aws-signingName: codeartifact
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/codeartifact-2018-09-22.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://codeartifact.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodeArtifact multi-region endpoint
- url: https://codeartifact.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The CodeArtifact multi-region endpoint
- url: http://codeartifact.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodeArtifact endpoint for China (Beijing) and China (Ningxia)
- url: https://codeartifact.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The CodeArtifact endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Repositories
paths:
  /v1/repositories:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListRepositories
      description: Returns a list of RepositorySummary objects. Each RepositorySummary contains information about a repository in the specified Amazon Web Services account and that matches the input parameters.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListRepositoriesResult'
              examples:
                ListRepositories200Example:
                  summary: Default ListRepositories 200 response
                  x-microcks-default: true
                  value:
                    repositories: my-repo
                    nextToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.example
        '480':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                ListRepositories480Example:
                  summary: Default ListRepositories 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
              examples:
                ListRepositories481Example:
                  summary: Default ListRepositories 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
              examples:
                ListRepositories482Example:
                  summary: Default ListRepositories 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
              examples:
                ListRepositories483Example:
                  summary: Default ListRepositories 483 response
                  x-microcks-default: true
                  value: '500123'
      parameters:
      - name: repository-prefix
        in: query
        required: false
        description: ' A prefix used to filter returned repositories. Only repositories with names that start with <code>repositoryPrefix</code> are returned.'
        schema:
          type: string
          pattern: '[A-Za-z0-9][A-Za-z0-9._\-]{1,99}'
          minLength: 2
          maxLength: 100
      - name: max-results
        in: query
        required: false
        description: ' The maximum number of results to return per page. '
        schema:
          type: integer
          minimum: 1
          maximum: 1000
      - name: next-token
        in: query
        required: false
        description: ' The token for the next set of results. Use the value returned in the previous response in the next request to retrieve the next set of results. '
        schema:
          type: string
          pattern: \S+
          minLength: 1
          maxLength: 2000
      - name: maxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: nextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      summary: Amazon CodeArtifact List Repositories
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Repositories
components:
  parameters:
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
  schemas:
    ThrottlingException: {}
    AccountId:
      type: string
      pattern: '[0-9]{12}'
      minLength: 12
      maxLength: 12
    Arn:
      type: string
      pattern: \S+
      minLength: 1
      maxLength: 1011
    RepositoryName:
      type: string
      pattern: '[A-Za-z0-9][A-Za-z0-9._\-]{1,99}'
      minLength: 2
      maxLength: 100
    ValidationException: {}
    Description:
      type: string
      pattern: \P{C}*
      maxLength: 1000
    RepositorySummary:
      type: object
      properties:
        name:
          allOf:
          - $ref: '#/components/schemas/RepositoryName'
          - description: ' The name of the repository. '
        administratorAccount:
          allOf:
          - $ref: '#/components/schemas/AccountId'
          - description: ' The Amazon Web Services account ID that manages the repository. '
        domainName:
          allOf:
          - $ref: '#/components/schemas/DomainName'
          - description: ' The name of the domain that contains the repository. '
        domainOwner:
          allOf:
          - $ref: '#/components/schemas/AccountId'
          - description: ' The 12-digit account number of the Amazon Web Services account that owns the domain. It does not include dashes or spaces. '
        arn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: ' The ARN of the repository. '
        description:
          allOf:
          - $ref: '#/components/schemas/Description'
          - description: ' The description of the repository. '
        createdTime:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: A timestamp that represents the date and time the repository was created.
      description: ' Details about a repository, including its Amazon Resource Name (ARN), description, and domain information. The <a href="https://docs.aws.amazon.com/codeartifact/latest/APIReference/API_ListRepositories.html">ListRepositories</a> operation returns a list of <code>RepositorySummary</code> objects. '
    PaginationToken:
      type: string
      pattern: \S+
      minLength: 1
      maxLength: 2000
    InternalServerException: {}
    ListRepositoriesResult:
      type: object
      properties:
        repositories:
          allOf:
          - $ref: '#/components/schemas/RepositorySummaryList'
          - description: ' The returned list of <a href="https://docs.aws.amazon.com/codeartifact/latest/APIReference/API_RepositorySummary.html">RepositorySummary</a> objects. '
        nextToken:
          allOf:
          - $ref: '#/components/schemas/PaginationToken'
          - description: ' If there are additional results, this is the token for the next set of results. '
    AccessDeniedException: {}
    DomainName:
      type: string
      pattern: '[a-z][a-z0-9\-]{0,48}[a-z0-9]'
      minLength: 2
      maxLength: 50
    Timestamp:
      type: string
      format: date-time
    RepositorySummaryList:
      type: array
      items:
        $ref: '#/components/schemas/RepositorySummary'
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/codeartifact/
x-hasEquivalentPaths: true
